 

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as DemoRouteImport } from './routes/_demo'
import { Route as ProtectedIndexRouteImport } from './routes/_protected.index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected.settings'
import { Route as ProtectedPrivacyRouteImport } from './routes/_protected.privacy'
import { Route as ProtectedImportRouteImport } from './routes/_protected.import'
import { Route as ProtectedExportRouteImport } from './routes/_protected.export'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ProtectedBatchRouteImport } from './routes/_protected.batch'
import { Route as DemoDemoRouteImport } from './routes/_demo.demo'
import { Route as ProtectedBatchIndexRouteImport } from './routes/_protected.batch.index'
import { Route as ProtectedBucketSlugRouteImport } from './routes/_protected.bucket.$slug'
import { Route as ProtectedBatchBatchIdRouteImport } from './routes/_protected.batch.$batchId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/_demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPrivacyRoute = ProtectedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedImportRoute = ProtectedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedExportRoute = ProtectedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBatchRoute = ProtectedBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => ProtectedRoute,
} as any)
const DemoDemoRoute = DemoDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => DemoRoute,
} as any)
const ProtectedBatchIndexRoute = ProtectedBatchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedBatchRoute,
} as any)
const ProtectedBucketSlugRoute = ProtectedBucketSlugRouteImport.update({
  id: '/bucket/$slug',
  path: '/bucket/$slug',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBatchBatchIdRoute = ProtectedBatchBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => ProtectedBatchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/sign-in': typeof SignInRoute
  '/demo': typeof DemoDemoRoute
  '/batch': typeof ProtectedBatchRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/export': typeof ProtectedExportRoute
  '/import': typeof ProtectedImportRoute
  '/privacy': typeof ProtectedPrivacyRoute
  '/settings': typeof ProtectedSettingsRoute
  '/batch/$batchId': typeof ProtectedBatchBatchIdRoute
  '/bucket/$slug': typeof ProtectedBucketSlugRoute
  '/batch/': typeof ProtectedBatchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/sign-in': typeof SignInRoute
  '/demo': typeof DemoDemoRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/export': typeof ProtectedExportRoute
  '/import': typeof ProtectedImportRoute
  '/privacy': typeof ProtectedPrivacyRoute
  '/settings': typeof ProtectedSettingsRoute
  '/batch/$batchId': typeof ProtectedBatchBatchIdRoute
  '/bucket/$slug': typeof ProtectedBucketSlugRoute
  '/batch': typeof ProtectedBatchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_demo': typeof DemoRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_demo/demo': typeof DemoDemoRoute
  '/_protected/batch': typeof ProtectedBatchRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/export': typeof ProtectedExportRoute
  '/_protected/import': typeof ProtectedImportRoute
  '/_protected/privacy': typeof ProtectedPrivacyRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/batch/$batchId': typeof ProtectedBatchBatchIdRoute
  '/_protected/bucket/$slug': typeof ProtectedBucketSlugRoute
  '/_protected/batch/': typeof ProtectedBatchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/demo'
    | '/batch'
    | '/dashboard'
    | '/export'
    | '/import'
    | '/privacy'
    | '/settings'
    | '/batch/$batchId'
    | '/bucket/$slug'
    | '/batch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/demo'
    | '/dashboard'
    | '/export'
    | '/import'
    | '/privacy'
    | '/settings'
    | '/batch/$batchId'
    | '/bucket/$slug'
    | '/batch'
  id:
    | '__root__'
    | '/_demo'
    | '/_protected'
    | '/sign-in'
    | '/_demo/demo'
    | '/_protected/batch'
    | '/_protected/dashboard'
    | '/_protected/export'
    | '/_protected/import'
    | '/_protected/privacy'
    | '/_protected/settings'
    | '/_protected/'
    | '/_protected/batch/$batchId'
    | '/_protected/bucket/$slug'
    | '/_protected/batch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DemoRoute: typeof DemoRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demo': {
      id: '/_demo'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/privacy': {
      id: '/_protected/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof ProtectedPrivacyRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/import': {
      id: '/_protected/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ProtectedImportRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/export': {
      id: '/_protected/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ProtectedExportRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/batch': {
      id: '/_protected/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof ProtectedBatchRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_demo/demo': {
      id: '/_demo/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoDemoRouteImport
      parentRoute: typeof DemoRoute
    }
    '/_protected/batch/': {
      id: '/_protected/batch/'
      path: '/'
      fullPath: '/batch/'
      preLoaderRoute: typeof ProtectedBatchIndexRouteImport
      parentRoute: typeof ProtectedBatchRoute
    }
    '/_protected/bucket/$slug': {
      id: '/_protected/bucket/$slug'
      path: '/bucket/$slug'
      fullPath: '/bucket/$slug'
      preLoaderRoute: typeof ProtectedBucketSlugRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/batch/$batchId': {
      id: '/_protected/batch/$batchId'
      path: '/$batchId'
      fullPath: '/batch/$batchId'
      preLoaderRoute: typeof ProtectedBatchBatchIdRouteImport
      parentRoute: typeof ProtectedBatchRoute
    }
  }
}

interface DemoRouteChildren {
  DemoDemoRoute: typeof DemoDemoRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoDemoRoute: DemoDemoRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface ProtectedBatchRouteChildren {
  ProtectedBatchBatchIdRoute: typeof ProtectedBatchBatchIdRoute
  ProtectedBatchIndexRoute: typeof ProtectedBatchIndexRoute
}

const ProtectedBatchRouteChildren: ProtectedBatchRouteChildren = {
  ProtectedBatchBatchIdRoute: ProtectedBatchBatchIdRoute,
  ProtectedBatchIndexRoute: ProtectedBatchIndexRoute,
}

const ProtectedBatchRouteWithChildren = ProtectedBatchRoute._addFileChildren(
  ProtectedBatchRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedBatchRoute: typeof ProtectedBatchRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedExportRoute: typeof ProtectedExportRoute
  ProtectedImportRoute: typeof ProtectedImportRoute
  ProtectedPrivacyRoute: typeof ProtectedPrivacyRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedBucketSlugRoute: typeof ProtectedBucketSlugRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBatchRoute: ProtectedBatchRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedExportRoute: ProtectedExportRoute,
  ProtectedImportRoute: ProtectedImportRoute,
  ProtectedPrivacyRoute: ProtectedPrivacyRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedBucketSlugRoute: ProtectedBucketSlugRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DemoRoute: DemoRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
