/**
 * LLM port interface for suggestion generation.
 *
 * This port abstracts the LLM provider (OpenAI, stub, etc.) from the business logic.
 * Implementations live in the adapters/ folder.
 */

/**
 * User bucket info passed to LLM for dynamic prompt building.
 */
export interface BucketInfo {
	slug: string;
	description: string;
}

/**
 * A suggestion generated by the LLM.
 */
export interface Suggestion {
	bucket: string; // Now a dynamic slug, not a fixed type
	text: string;
}

/**
 * Configuration for creating an LLM client.
 */
export interface LlmClientConfig {
	provider: 'openai' | 'stub';
	accountId?: string;
	gatewayId?: string;
	apiKey?: string;
}

/**
 * LLM client interface for generating suggestions.
 */
export interface LlmClient {
	/**
	 * Generate a suggestion for a single term.
	 *
	 * @param term - The term to generate a suggestion for
	 * @param buckets - The user's buckets for dynamic prompt building
	 * @returns A suggestion with bucket and text
	 * @throws Error if the LLM call fails
	 */
	suggestOne(term: string, buckets: BucketInfo[]): Promise<Suggestion>;
}

/**
 * Provider type for suggestion generation.
 */
export type SuggestionProvider = 'openai' | 'stub' | 'disabled';
