/**
 * LLM port interface for suggestion generation.
 *
 * This port abstracts the LLM provider (OpenAI, stub, etc.) from the business logic.
 * Implementations live in the adapters/ folder.
 */

import type { Bucket } from '@append/contracts/types';

/**
 * A suggestion generated by the LLM.
 */
export interface Suggestion {
	bucket: Bucket;
	text: string;
}

/**
 * Configuration for creating an LLM client.
 */
export interface LlmClientConfig {
	provider: 'openai' | 'stub';
	accountId?: string;
	gatewayId?: string;
	apiKey?: string;
}

/**
 * LLM client interface for generating suggestions.
 */
export interface LlmClient {
	/**
	 * Generate a suggestion for a single term.
	 *
	 * @param term - The term to generate a suggestion for
	 * @returns A suggestion with bucket and text
	 * @throws Error if the LLM call fails
	 */
	suggestOne(term: string): Promise<Suggestion>;
}

/**
 * Provider type for suggestion generation.
 */
export type SuggestionProvider = 'openai' | 'stub' | 'disabled';
